apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: ELKStack
spec:
  description: ELK Stack configuration integrated with RagFlow services
  tags:
    - Logging
    - Monitoring
    - Analytics
  services:
    - name: elk-elasticsearch
      template: PREBUILT
      spec:
        source:
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
          command:
            - /bin/bash
          args:
            - -c
            - |
              groupadd -g 1000 elasticsearch || true
              useradd -u 1000 -g 1000 -d /usr/share/elasticsearch elasticsearch || true
              chown -R elasticsearch:elasticsearch /usr/share/elasticsearch
              su elasticsearch -c "cd /usr/share/elasticsearch && ./bin/elasticsearch-keystore create"
              su elasticsearch -c "cd /usr/share/elasticsearch && ./bin/elasticsearch"
        env:
          discovery.type:
            default: single-node
          xpack.security.enabled:
            default: "false"
          xpack.security.http.ssl.enabled:
            default: "false"
          xpack.security.transport.ssl.enabled: 
            default: "false"
          http.host:
            default: "0.0.0.0"
          network.host:
            default: "0.0.0.0"
          ES_JAVA_OPTS:
            default: "-Xms512m -Xmx512m"
          ELASTIC_PASSWORD:
            default: "${ELASTIC_PASSWORD}"
              
        ports:
          - id: elasticsearch
            port: 9200
            type: HTTP
        volumes:
          - id: data
            dir: /usr/share/elasticsearch/data


    - name: kibana
      template: PREBUILT
      spec:
        source:
          image: docker.elastic.co/kibana/kibana:8.15.0
          command:
            - /bin/sh
          args:
            - -c
            - |
              # 直接啟動 Kibana，環境變數由外部帶入
              bin/kibana --allow-root
        environment:
          ELASTICSEARCH_HOSTS:
            default: "http://elk-elasticsearch.zeabur.internal:9200"
          NODE_OPTIONS:
            default: "--no-node-snapshot --no-experimental-fetch"
          SERVER_HOST:
            default: "0.0.0.0"
          SERVER_NAME:
            default: "kibana"
        ports:
          - id: kibana
            port: 5601
            type: HTTP
